# docker-compose.yml
services:
  livox:
    build: .
    # Host network & USB access for the LiDAR
    network_mode: host
    privileged: true
    ipc: host
    tty: true
    stdin_open: true
    # ⬇️  Bind-mount your workspaces so you can edit freely
    volumes:
      - ./ros2_ws:/ros2_ws:rw           # whole workspace
      - ./Livox-SDK2:/Livox-SDK2:rw 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/data:ro  
      - /mnt/wslg/.X11-unix:/mnt/wslg/.X11-unix:ro
      - /mnt/wslg/.X11-unix:/tmp/.X11-unix:ro      # legacy path
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}    # SDK sources (optional)
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        cd /ros2_ws &&
        colcon build --symlink-install --cmake-args -DHUMBLE_ROS=humble &&
        source install/setup.bash &&
        ros2 daemon start &&
        ros2 launch livox_ros_driver2 msg_MID360_launch.py
      "
    environment:
      - LIVOX_LOG_LEVEL=DEBUG
      - RCL_LOG_LEVEL=DEBUG
      - ROS_DOMAIN_ID=1
      - ROS_LOCALHOST_ONLY=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - DATASET_DIR=/data
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR